### ISSUE TITLE
Transformation Matrix Stack

### ISSUE THREAD

**Issue by danfitz7** [jminardi/mecode#11]
A transformation hierarchy similar to that used by the [Processing language for rendering using a stack of coordinate transform matrices](http://processing.org/reference/pushMatrix_.html) may be useful in mecode.

This would consist of two primary functions: `push_matrix()` and `pop_matrix()`, which manipulate a stack of matrix transforms which are all applied to the currently used coordinates.

For example, it may be useful to define some printed feature in local absolute (or relative) coordinates but print the feature in multiple places with different rotations, etc. The main code would push the transform matrix for a unique position/orientation of the feature to the stack,  call the code to print the feature, then pop the transform off the stack and continue in its "world" coordinates. Then all the code for the feature can operate in "local" coordinates. 

In implementation, this functionality can be achieved by using relative movements for all such subfeatures, but calculating the relative distances from coordinate counter variables which correspond to local absolute position. The manipulation of these counters is based on the current transformation matrix stack.

This system allows for an elegant coordinate systems hierarchy, with features and sub features defined intuitively in their local coordinates systems.

**Comment by jminardi** [comment]
Closed by #27
