### ISSUE TITLE
Python 3 Compatibility

### ISSUE THREAD

**Issue by sjkelly** [jminardi/mecode#2]
I'd like to be able to use Python3. The line below typically helps bridge between Python 2 and Python 3.

`from __future__ import absolute_import, division, print_function, unicode_literals`

it also seems Mayavi does not work with Python 3 yet, see https://github.com/enthought/mayavi/issues/84.

Will this break anything on the windows computers?

**Comment by fake-name** [comment]
Py3 is a real need.

**Comment by jminardi** [comment]
Mecode has been tested and passing on Py3 for a few years now:

https://travis-ci.org/jminardi/mecode/builds/318175904

Is there a particular issue you are having with Py3? If so we can fix that and capture it in a test.

**Comment by DerAndere1** [comment]
There are still certain incompatibilities with Py3 which have been fixed in the [serial_fix branch of my mecode fork](https://github.com/DerAndere1/mecode/tree/serial_fix ). See discussion on issue #66
