### ISSUE TITLE
"python setup.py install" errors out (Python 3.4)

### ISSUE THREAD

**Issue by polycopter** [jminardi/mecode#31]
running install
running bdist_egg
running egg_info
creating mecode.egg-info
writing top-level names to mecode.egg-info\top_level.txt
writing dependency_links to mecode.egg-info\dependency_links.txt
writing mecode.egg-info\PKG-INFO
writing manifest file 'mecode.egg-info\SOURCES.txt'
reading manifest file 'mecode.egg-info\SOURCES.txt'
writing manifest file 'mecode.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
creating build
creating build\lib
creating build\lib\mecode
copying mecode\main.py -> build\lib\mecode
copying mecode\matrix.py -> build\lib\mecode
copying mecode\printer.py -> build\lib\mecode
copying mecode\profilometer_parse.py -> build\lib\mecode
copying mecode\utils.py -> build\lib\mecode
copying mecode\__init__.py -> build\lib\mecode
creating build\lib\mecode\devices
copying mecode\devices\base_serial_device.py -> build\lib\mecode\devices
copying mecode\devices\efd_pressure_box.py -> build\lib\mecode\devices
copying mecode\devices\keyence_line_scanner.py -> build\lib\mecode\devices
copying mecode\devices\keyence_micrometer.py -> build\lib\mecode\devices
copying mecode\devices\keyence_profilometer.py -> build\lib\mecode\devices
copying mecode\devices\__init__.py -> build\lib\mecode\devices
creating build\bdist.win32
creating build\bdist.win32\egg
creating build\bdist.win32\egg\mecode
creating build\bdist.win32\egg\mecode\devices
copying build\lib\mecode\devices\base_serial_device.py -> build\bdist.win32\egg\
mecode\devices
copying build\lib\mecode\devices\efd_pressure_box.py -> build\bdist.win32\egg\me
code\devices
copying build\lib\mecode\devices\keyence_line_scanner.py -> build\bdist.win32\eg
g\mecode\devices
copying build\lib\mecode\devices\keyence_micrometer.py -> build\bdist.win32\egg\
mecode\devices
copying build\lib\mecode\devices\keyence_profilometer.py -> build\bdist.win32\eg
g\mecode\devices
copying build\lib\mecode\devices\__init__.py -> build\bdist.win32\egg\mecode\dev
ices
copying build\lib\mecode\main.py -> build\bdist.win32\egg\mecode
copying build\lib\mecode\matrix.py -> build\bdist.win32\egg\mecode
copying build\lib\mecode\printer.py -> build\bdist.win32\egg\mecode
copying build\lib\mecode\profilometer_parse.py -> build\bdist.win32\egg\mecode
copying build\lib\mecode\utils.py -> build\bdist.win32\egg\mecode
copying build\lib\mecode\__init__.py -> build\bdist.win32\egg\mecode
byte-compiling build\bdist.win32\egg\mecode\devices\base_serial_device.py to bas
e_serial_device.cpython-34.pyc
byte-compiling build\bdist.win32\egg\mecode\devices\efd_pressure_box.py to efd_p
ressure_box.cpython-34.pyc
byte-compiling build\bdist.win32\egg\mecode\devices\keyence_line_scanner.py to k
eyence_line_scanner.cpython-34.pyc
byte-compiling build\bdist.win32\egg\mecode\devices\keyence_micrometer.py to key
ence_micrometer.cpython-34.pyc
byte-compiling build\bdist.win32\egg\mecode\devices\keyence_profilometer.py to k
eyence_profilometer.cpython-34.pyc
byte-compiling build\bdist.win32\egg\mecode\devices\__init__.py to __init__.cpyt
hon-34.pyc
byte-compiling build\bdist.win32\egg\mecode\main.py to main.cpython-34.pyc
byte-compiling build\bdist.win32\egg\mecode\matrix.py to matrix.cpython-34.pyc
byte-compiling build\bdist.win32\egg\mecode\printer.py to printer.cpython-34.pyc

byte-compiling build\bdist.win32\egg\mecode\profilometer_parse.py to profilomete
r_parse.cpython-34.pyc
byte-compiling build\bdist.win32\egg\mecode\utils.py to utils.cpython-34.pyc
byte-compiling build\bdist.win32\egg\mecode\__init__.py to __init__.cpython-34.p
yc
installing package data to build\bdist.win32\egg
running install_data
Traceback (most recent call last):
  File "setup.py", line 18, in <module>
    maintainer_email='jack@minardi.org',
  File "C:\Python34\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Python34\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Python34\lib\site-packages\setuptools\command\install.py", line 67, i
n run
    self.do_egg_install()
  File "C:\Python34\lib\site-packages\setuptools\command\install.py", line 109,
in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Python34\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Python34\lib\site-packages\setuptools\command\bdist_egg.py", line 181
, in run
    self.do_install_data()
  File "C:\Python34\lib\site-packages\setuptools\command\bdist_egg.py", line 133
, in do_install_data
    self.call_command('install_data', force=0, root=None)
  File "C:\Python34\lib\site-packages\setuptools\command\bdist_egg.py", line 147
, in call_command
    self.run_command(cmdname)
  File "C:\Python34\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Python34\lib\distutils\command\install_data.py", line 56, in run
    dir = convert_path(f[0])
  File "C:\Python34\lib\distutils\util.py", line 127, in convert_path
    raise ValueError("path '%s' cannot end with '/'" % pathname)
ValueError: path './mecode/' cannot end with '/'

**Comment by jminardi** [comment]
Can you checkout the `fix-trailing-slash` branch and see if that works for you?

**Comment by polycopter** [comment]
OK, I will try

**Comment by polycopter** [comment]
that seems to have fixed the problem, no errors reported. thanks!

**Comment by jminardi** [comment]
Closed by #33
