### ISSUE TITLE
How to set up Mecode software on my laptop?

### ISSUE THREAD

**Issue by soychemi** [jminardi/mecode#44]
It is very diffifcult to find the Mecode software here.
I download the Mecode software, but don't find the setup file.
How to set it up?

**Comment by jminardi** [comment]
The easiest way to install mecode is with pip:

```
$ sudo pip install mecode
```

If you want to install it from source, use the instructions in the readme:

```
$ git clone https://github.com/jminardi/mecode.git
$ cd mecode
$ pip install -r requirements.txt
$ python setup.py install
```
