### ISSUE TITLE
real time control using mecode.G(direct_write=True, direct_write_mode="serial") with fix

### ISSUE THREAD

**Issue by DerAndere1** [jminardi/mecode#66]
**Steps to reproduce issue**
1. connect your computer (via USB2.0) to a [controller board featuring a Microchip Atmega AVR microcontroller that is designed to reset upon serial connection](https://de.gearbest.com/3d-printer-parts/pp_540286.html) and that runs [marlin firmware](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x).
2. Run a Python3 script (I use the Python 3.7 interpreter CPython under MS Windows 10 64 bit) which contains a `mecode.G(direct_write=True)` command, e.g. listing 1:
```
import mecode
g = mecode.G(direct_write=True, direct_write_mode="serial", printer_port="COM3", baudrate=115200)   # realtime communication via serial communication at port COMx (with x=3) under MS Windows. See https://github.com/jminardi/mecode/blob/master/mecode/main.py .
g.write("M302 S0")   # send g-Code. Here: allow cold extrusion. Danger: Make sure extruder is clean without filament inserted 
g.move(10, 10, 10)   # move 10mm in x and 10mm in y and 10mm in z
g.retract(10)   # move extruder motor
```  
**Expected behaviour:**
- I expected that all stepper motors would move 
- I would like to find documentation on how to create a socket and get its port number in order to use it with `mecode.G(direct_write=True)`  as an alternative

**Observed behaviour:**
- Missing documentation on how to use `mecode.G(direct_write=True)`
- console output: `G91`  and some Error
- controller board resets, but no motor movement.

**Possible Solution:**
Use [my fork of mecode](https://github.com/DerAndere1/mecode) which provides fixes (see branch [serial_fix](https://github.com/DerAndere1/mecode/tree/serial_fix))
and add the following lines of code after the last command of the Python script that communicates with the controller board (e.g. append to listing 1, see above): 
```
import time
time.sleep(12)
```
If someone confirms my issues I can create a pull request

**Comment by jminardi** [comment]
The following works for me:

```python

    # mecode object
    g = G(
            print_lines=False,
            aerotech_include=False,
            direct_write=True,
            direct_write_mode='serial',
            printer_port="/dev/tty.usbmodem1411",
            #printer_port="COM13",  #use for windows host machine
    )
```

This is on python 2.7, although I think it should work with python 3.x

What is the fix you mentioned to get it to work?

**Comment by DerAndere1** [comment]
The diff is here:
https://github.com/jminardi/mecode/compare/master...DerAndere1:serial_fix#diff-7ffff7cfc8c0098f97023392516340e0L125

I guess for full python 3 compatibility, my key change was to add `.decode("utf-8")` to main.py [line 259](https://github.com/jminardi/mecode/blob/13eef1e2a173584badf9a3ac0f231497fd5945c6/mecode/printer.py#L259) and [line 358](https://github.com/jminardi/mecode/blob/13eef1e2a173584badf9a3ac0f231497fd5945c6/mecode/printer.py#L358) :
```
r = self.get_response("M114").decode("utf-8")
line = self.s.readline().decode("utf-8")
```
Instead of those changes, for python 2 compatibility I guess (not tested) a better solution could be to change `statement_in` to `statement)` in main.py [lines 972](https://github.com/jminardi/mecode/blob/13eef1e2a173584badf9a3ac0f231497fd5945c6/mecode/main.py#L972) and [line 974](https://github.com/jminardi/mecode/blob/13eef1e2a173584badf9a3ac0f231497fd5945c6/mecode/main.py#L974) . Then your encode2to3() and decode2to3() code in main.py would do the encoding depending on python version, right?

My second problem was that your loop in printer.py [line 125](https://github.com/jminardi/mecode/blob/13eef1e2a173584badf9a3ac0f231497fd5945c6/mecode/printer.py#L125) did recognize when my MCU finished restarting and the timeout stoped the serial connection. So I removed that loop and instead  changed [printer.py line 114](https://github.com/jminardi/mecode/blob/13eef1e2a173584badf9a3ac0f231497fd5945c6/mecode/printer.py#L114) from:  
`self.s = serial.Serial(self.port, self.baudrate, timeout=3)`
to:
```
self.s = serial.Serial(self.port, self.baudrate, timeout=6)
sleep(5)
```

**Comment by DerAndere1** [comment]
I updated my serial_fix branch and edited my comment above accordingly. Tested with Python3 only but It uses decode2To3 so Python 2 should also work.

**Comment by DerAndere1** [comment]
At least with Python 3.x, pySerial's `serial.read(data)` and `serial.write(data)` [requires that data to be transferred is a `bytes` object (or compatible type such as `bytearray`)](https://pyserial.readthedocs.io/en/latest/pyserial_api.html) . That is why for all occurances of `s.write()` and `s.read()` in mecode, the data to be sent should first be encoded like this: data.encode('utf-8') and received byte data has to be decoded to obtain unicode strings: `data.decode('utf-8')`. Along those lines, the tests have to be adjusted to make all data is always a byte object.:  

https://github.com/jminardi/mecode/blob/13eef1e2a173584badf9a3ac0f231497fd5945c6/mecode/tests/test_printer.py#L24
should read
`        self.p.s.readline.return_value = encode2to3('ok\n', utf-8)`

https://github.com/jminardi/mecode/blob/13eef1e2a173584badf9a3ac0f231497fd5945c6/mecode/tests/test_printer.py#L57
`        self.p.sendline(testline)`
https://github.com/jminardi/mecode/blob/13eef1e2a173584badf9a3ac0f231497fd5945c6/mecode/tests/test_printer.py#L56
should read 
`        self.p.s.write.assert_called_with(encode2to3('N1 no new line*44\n'))`

similarly, following lines have to be changed:
https://github.com/jminardi/mecode/blob/13eef1e2a173584badf9a3ac0f231497fd5945c6/mecode/tests/test_printer.py#L63
https://github.com/jminardi/mecode/blob/13eef1e2a173584badf9a3ac0f231497fd5945c6/mecode/tests/test_printer.py#L66

**Comment by jminardi** [comment]
@DerAndere1 Do you believe your suggested changes are still needed? I do not current have access to a serial connected 3d printer
